# Generated by Django 5.0 on 2024-04-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_promotion_alter_promotion_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promotion',
        ),
    ]
